[package]
name = "mandelbrot_cli"
version = "0.1.0"
edition = "2021"
description = "Lib and CLI for visualisation of the Mandelbrot fractal."
license = "GPL-2.0-only"
readme = "readme.md"
repository = ""

[dependencies]
image = "0.25.2"
num_cpus = "1.16.0"
